GET http://localhost:5162

###
GET http://localhost:5162/games

###
GET http://localhost:5162/games/2

###
POST http://localhost:5162/games
Content-Type: application/json

{
  "name": "Grand Turismo",
  "price": 99.99,
  "genre": "Racing",
  "releaseDate": "2020-12-12"
}

### CHANGING PRICE FROM 19.99 TO 29.99 AND TITLE TO Minecraft 2 AND RELEASE DATE TO 2024-7-23
PUT http://localhost:5162/games/2
Content-Type: application/json

{
  "name": "Minecraft 2",
  "genre": "Sandbox",
  "price": 29.99,
  "releaseDate": "2024-07-23"
}

### DELETE GAME WITH ID 3
DELETE http://localhost:5162/games/3

### INVALID POST REQUEST, MISSING NAME
POST http://localhost:5162/games
Content-Type: application/json

{
  "price": 99.99,
  "genre": "Racing",
  "releaseDate": "2020-12-12"
}